services:
  - type: web
    name: somali-ai-dataset
    env: static
    buildCommand: echo "Static site ready"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html